# Site settings
title: Clean Blog
header-img: home-bg.jpg
email: your-email@yourdomain.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/blog"
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  StartBootstrap
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","Gulpfile.js","package.json","README.md", ".asset-cache"]

gems:
  - jekyll-assets
  - jekyll-angular
  - jekyll-paginate
  - jekyll-feed
  - jekyll-coffeescript

assets:
  compress:
    css:
      development: false
      production: true
    js:
      development: false
      production: true
  debug: true
  cache: .asset-cache
  cdn: false
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: ""
  autowrite: false
  autoprefixer:
    browsers: ["> 1%","last 4 versions","IE > 8"]
  assets:
    - "*.png"
    - "*.jpg"
    - "*.svg"
    - "*.ttf"
    - "*.eot"
    - "*.woff"
    - "bundle.css"
  digest: true
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  features:
    liquid: false
    integrity: true
    automatic_img_size: true
    automatic_img_alt : true

asset_bundler:
  compress:
    js: uglifyjs
